### PR TITLE
Release 0.4

### PR DESCRIPTION
**Pull request by humitos**
This release fixes all the known issues and adds 95% test coverage.

### CODE REVIEW

**Comment by ericholscher** [comment]
This should probably be using the changelog generation scripts from the `rtfd/common` repo no? I think that would likely make them more useful and easier to generate.

**Comment by humitos** [comment]
@ericholscher kind of. That script is tied to a `setup.cfg` and some things needs to be adapted to use it directly. Although, I just commented that part from `tasks.py` and ran the changelog part only.

I'm pushing the new changelog for 0.4.

**Comment by humitos** [comment]
I think we can wait for #44 and #40 to be merged and we are ready to go.

**Comment by humitos** [comment]
It seems that #40 will take some time to understand Sphinx's internal better and maybe do a different approach to solve the problem. I think we should deploy 0.4 with what we have already.

**Comment by acozine** [comment]
@humitos if you could include #46 in the release, I'd be very grateful!

**Comment by acozine** [comment]
@humitos fantastic work - do you have a timeline for merging this PR and releasing 0.4?

**Comment by humitos** [comment]
@acozine v0.4 is released and available in PyPI. You should be able to install it from there. Hopefully, everything works as we tested! Thanks for your support.

**Pull request merged**
