### PR TITLE
Package license

### LINKED ISSUE #17: Add license to PyPI package
When running this command, it should show the proper license.

```
$ pip show sphinx-notfound-page
Name: sphinx-notfound-page
Version: 0.2.1
Summary: Sphinx extension to build a 404 page with absolute URLs
Home-page: https://github.com/rtfd/sphinx-notfound-page
Author: Manuel Kaufmann
Author-email: humitos@gmail.com
License: UNKNOWN
Location: /home/humitos/rtfd/code/sphinx-notfound-page
Requires: sphinx
Required-by: 
(readthedocs.org) 
$ 
```

### PR DESCRIPTION
**Pull request by humitos**
Closes #17

### CODE REVIEW

**Comment by stsewd** [comment]
Actually you need to have a MANIFEST.in file to really package the license, like https://github.com/rtfd/readthedocs-sphinx-ext/pull/65/files

**Comment by humitos** [comment]
It seems that's not needed and Python has its own mechanism to detect that file exists and add it automatically when running `python setup.py sdist`

    adding license file "LICENSE" (matched pattern "LICEN[CS]E*")

**Comment by humitos** [comment]
I add it anyway and also exclude `common/` for being packaged and distributed.

**Comment by stsewd** [comment]
I think that was with recent versions of setuptools (includes readme too), can't remember what was needed to used them.

**Pull request merged**
